In [8]:
from fpdf import FPDF
bobo = 'melanie'
pdf = FPDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(60, 10, f'Hello World! {bobo}', 1, align='C')
pdf.output('tuto1.pdf', 'F')

''

In [51]:
ar = [10, 20, 20, 10, 10, 30, 50, 10, 20]
n=9
if len(ar)==n:
    sockMerchant(n, ar)


3


In [50]:
def sockMerchant(n, ar):
    lista_unicos = []
    for elem in ar:
        if elem not in lista_unicos:
            lista_unicos.append(elem)
    pares = count_items(ar, lista_unicos)
    print(pares)

In [49]:
def count_items(ar, lista_unicos):    
    pares_totales = 0
    for item in lista_unicos:
        value = 0
        for elem in ar:
            if item == elem:
                value += 1
        if value>1:
            if value%2!=0:
                value -= 1
            pares = value//2
        else:
            pares = 0
        pares_totales+=pares
    return pares_totales

In [53]:
steps = 8
path = 'UDDDUDUU'

weights = {'D':-1, 'U':1}

In [67]:
countingValleys(steps, path)

1


In [66]:
def countingValleys(steps, path):
    value = 0
    valles = 0
    reinicio = True
    for elem in path:
        value += weights[elem]
        if value < 0:
            if reinicio:
                valles += 1
                reinicio = False
        elif value >= 0:
            reinicio = True
    print(valles)

In [70]:
import numpy as np

In [101]:
array_x = np.array([[1, 1, 1, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0],
                  [0, 0, 2, 4, 4, 0],
                  [0, 0, 0, 2, 0, 0],
                  [0, 0, 1, 2, 4, 0]])

In [102]:
dim_clock = [3, 3]
array_x.shape
pos_clock = [array_x.shape[0]+1-dim_clock[0], array_x.shape[1]+1-dim_clock[1]]
cont_sumas = np.zeros(pos_clock)

for i in range(pos_clock[0]):
    for j in range(pos_clock[1]):
        print(array_x[i:dim_clock[0]+i, j:dim_clock[1]+j])
        cont_sumas[i, j] = np.sum(array_x[i:dim_clock[0]+i, j:dim_clock[1]+j])
        
cont_sumas

[[1 1 1]
 [1 1 1]]
[[1 1 0]
 [1 1 0]]
[[1 0 0]
 [1 0 0]]
[[0 0 0]
 [0 0 0]]
[[0 1 0]
 [0 0 2]]
[[1 0 0]
 [0 2 4]]
[[0 0 0]
 [2 4 4]]
[[0 0 0]
 [4 4 0]]
[[1 1 1]
 [0 0 0]]
[[1 1 0]
 [0 0 2]]
[[1 0 0]
 [0 2 0]]
[[0 0 0]
 [2 0 0]]
[[0 0 2]
 [0 0 1]]
[[0 2 4]
 [0 1 2]]
[[2 4 4]
 [1 2 4]]
[[4 4 0]
 [2 4 0]]


array([[ 7.,  5.,  2.,  0.],
       [ 6.,  9., 11.,  8.],
       [ 5., 10., 13., 10.],
       [ 3., 11., 19., 16.]])